alphawrite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('essay.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

essay/urls.py
from django.urls import path
from . import views

app_name = 'essay'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('build', views.build, name='build'),
    path('questions', views.questions, name='questions'),
    path('draft', views.draft, name='draft'),
    path('read', views.read, name='read'),
    path('parse', views.parse, name='parse'),
    path('ideas', views.ideas, name='ideas'),
]

essay/models.py
import datetime
from collections import Counter

from django.db import models
from django.utils import timezone
import random
from .dictionary import Question
import spacy


class Thesis:
    def __init__(self, ideas):
        self.ideas = ideas

    def __str__(self):
        return self.build()

    def prepare(self):

        # build evidences

        fact = self.ideas.get("fact", "")

        definition = self.ideas.get("definition", "")

        quality = self.ideas.get("quality", "")

        counterpoint = self.ideas.get("counterpoint", "")

        evidences = [fact, definition, counterpoint]

        policy = self.ideas.get("policy", "")

        if quality and policy:
            argument = policy + " " + quality
        else:
            argument = policy + quality

        return {'argument': argument, 'evidences': evidences}


class Draft:
    def __init__(self, elements):
        self.type = ""
        self.structure = ""
        self.elements = elements
        self.argument = elements['argument']
        self.entities = elements['entities']
        self.claims = elements['claims']
        self.evidences = elements['evidences']

    def introduction(self):
        pass

    def generate(self):
        introduction = self.argument
        for c in self.claims:
            introduction += " " + c

        paragraphs = []

        paragraph_what = self.claims[0] + " " + self.evidences[0]
        paragraphs.append(paragraph_what)

        paragraph_nature = self.claims[1] + " " + self.evidences[1]
        paragraphs.append(paragraph_nature)

        if randrange(10) > 5:
            prefix_e = "One might object here that"
            prefix_c = "Nevertheless,"
        else:
            prefix_e = "On the one hand, I agree with some proponents that"
            prefix_c = "But on the other hand, I still insist that"
        counter_evidence = self.pack(prefix_e, self.evidences[2])
        counter_claim = self.pack(prefix_c, self.claims[2])

        paragraph_counter = counter_evidence + " " + counter_claim
        paragraphs.append(paragraph_counter)

        conclusion = introduction
        return {'introduction': introduction, 'paragraphs': paragraphs, 'conclusion': conclusion}

    def pack(self, prefix, sentence):
        packed = sentence
        first_word = packed.split(' ', 1)[0]
        if first_word not in self.entities:
            packed = packed[0].lower() + packed[1:]
        return prefix + " " + packed


# model for transition
class Transition:
    def __init__(self, category):
        self.category = category  # e.g., contrast

    def get_category(self):
        return self.category

    def get_phrases(self):
        """
        :param category: string
        :return (list): list of words in the given category
        """
        phrases = []

        cause_effect = ["Consequently", "Therefore", "Accordingly", "As a result",
                        "Hence", "Thus", "For this reason", "Due"]
        sequence = ["Furthermore", "In addition", "Moreover", "Finally",
                    "Again", "Until then", "In light of", "Again"]
        compare_contrast = ["similarly", "Likewise", "In the same fashion", "In the same way",
                            "In like manner", "Correspondingly", "Equally important", "Conversely", "In contrast",
                            "however", "On the contrary", "yet", "whereas"]
        example = ["For instance", "For example", "In fact", "Indeed", "of course",
                   "Equally important", "Specifically", "In other words"]
        purpose = ["Ultimately", "Evidently", "Without doubt", "Invariably", "To this end"]
        multiple = ["Couples with", "Together with", "vast array", "tapestry", "plethora"]

        if self.category == "cause_effect":
            phrases = cause_effect

        if self.category == "sequence":
            phrases = sequence

        return phrases

    def get_phrase(self):
        phrases = self.get_phrases()
        i = randrange(len(phrases))
        return phrases[i]


# model for active verbs
class Verb:
    def __init__(self, category):
        self.category = category

    def get_category(self):
        return self.category

    def get_verbs(self):
        """
        :param category: string
        :return (list): list of words in the given category
        """
        verbs = []

        literary = ["Consequently", "Therefore", "Accordingly", "As a result",
                    "Hence", "Thus", "For this reason", "Due"]
        research = ["Furthermore", "In addition", "Moreover", "Finally",
                    "Again", "Until then", "In light of", "Again"]
        beginnings = ["similarly", "Likewise", "In the same fashion", "In the same way",
                      "In like manner", "Correspondingly", "Equally important", "Conversely", "In contrast",
                      "however", "On the contrary", "yet", "whereas"]
        ideas = ["For instance", "For example", "In fact", "Indeed", "of course",
                 "Equally important", "Specifically", "In other words"]
        legal = ["Ultimately", "Evidently", "Without doubt", "Invariably", "To this end"]

        if self.category == "literary":
            verbs = literary

        if self.category == "beginnings":
            verbs = beginnings

        return verbs

    def get_verb(self):
        verbs = self.get_verbs()
        i = randrange(len(verbs))
        return verbs[i]


class Assignment:
    informative = ['inform', 'describe', 'define', 'review', 'notify', 'instruct', 'advise', 'announce', 'explain',
                   'demonstrate', 'illustrate', 'discuss', 'analyse', 'analyze']
    persuasive = ['persuade', 'convince', 'influence', 'argue', 'recommend', 'change', 'advocate', 'urge', 'defend',
                  'justify', 'support', 'to what extent', 'assess', 'evaluate', 'affect']

    subjects = ['Hitler', 'Mao', 'economic', 'finance']

    def __init__(self, assignment):
        self.purpose = "persuasive"
        self.topic = ""
        self.assignment = assignment

    def process(self):
        info = 0
        pers = 0
        for word in self.assignment.split():
            if word in self.informative:
                info += 1
            if word in self.persuasive:
                pers += 1
            if word in self.subjects:
                self.topic += word + " "
        if info > pers:
            self.purpose = "informative"

        return self

    def get_purpose(self):
        return self.purpose

    def get_topic(self):
        return self.topic


class Idea:
    def __init__(self, topic):
        self.topic = topic
        self.subject = ""
        self.verb = ""
        self.object = ""
        self.entities = ""
        self.processed = False
        self.questions = Question.dict

    def blocked(self):
        if '</script>' in self.topic:
            return True

        blacklist = [
            "test",
            "thisisatest",
            "whatsup",
        ]
        topic = ''.join(e for e in self.topic if e.isalnum()).lower()
        if topic.isdigit() or topic in blacklist or len(topic) < 2:
            return True

        if not self.processed:
            self.process()
        if not self.subject and not self.object and not len(self.entities):
            return True
        return False

    def process(self):
        if self.processed:
            return self

        nlp = spacy.load('en_core_web_sm')
        doc = nlp(self.topic)
        sentence = next(doc.sents)  # last sentence in prompt

        for word in sentence:
            if word.dep_ == 'nsubj':
                self.subject = word.text
            if word.dep_ in ['dobj', 'obj']:
                self.object = word.text
            if word.dep_ == 'ROOT':
                if word.pos_ == 'VERB':
                    self.verb = word.text.lower()
                if word.pos_ == 'NOUN' and not self.subject:
                    self.subject = word.text.lower()

        if self.subject:
            for chunk in doc.noun_chunks:
                if self.subject in chunk.text:
                    self.subject = chunk.text
                    break

        if self.object:
            for chunk in doc.noun_chunks:
                if self.object in chunk.text:
                    if 'What' not in chunk.text and 'Which' not in chunk.text:
                        self.object = chunk.text
                    break

        entities = []
        for ent in doc.ents:
            if ent.label_ in ['PERSON', 'ORG', 'EVENT', 'GPE', 'NORP']:
                entities.append(ent.text)

        ents = ""
        num_ents = len(entities)
        if num_ents:
            ents = entities[0]
            if num_ents == 2:
                ents += " and " + entities[1]
            elif num_ents > 2:  # 3 and more
                for i in range(1, num_ents - 1):
                    ents += ", " + entities[i]
                ents += ", and " + entities[num_ents - 1]

        self.entities = ents

        self.processed = True
        return self

    def generate_questions(self):
        q_fact = ['']
        q_definition = ['']
        q_quality = [''] * 2
        q_policy = ['']
        for badge, qs in self.questions.items():
            # replaced with subj, obj, and entities
            random.shuffle(qs)
            for question in qs:
                q = question.replace('{SUBJ}', '--' + self.subject + '--').replace('{OBJ}',
                                                                                   '--' + self.object + '--').replace(
                    '{ENTS}', '--' + self.entities + '--')
                if '----' not in q:
                    if '{F}' in q and not q_fact[0]:
                        q_fact[0] = q.replace('{F}', '').replace('--', '')
                    if '{D}' in q and not q_definition[0]:
                        q_definition[0] = q.replace('{D}', '').replace('--', '')

essay/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse, JsonResponse

from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Transition, Verb, Thesis, Assignment, Idea, Draft
from .article import Article


def index(request):
    return render(request, 'essay/topic.html')


def dashboard(request):
    topic = request.POST['topic']
    idea = Idea(topic)

    if idea.blocked():
        return render(request, 'essay/index.html', {'idea': idea})
    else:
        return render(request, 'essay/dashboard.html', {
            'idea': idea,
            'evidence_types': ['cloud', 'cloud-rain', 'cloud-sun'],
        })


def questions(request):
    topic = request.POST['topic']
    stasis = request.POST['stasis']
    idea = Idea(topic)

    if idea.blocked():
        return
    else:
        return JsonResponse(idea.generate_question(stasis))


def ideas(request):
    topic = request.POST['topic']
    idea = Idea(topic)

    if idea.blocked():
        return render(request, 'essay/topic.html', {'idea': idea})
    else:
        return render(request, 'essay/ideas.html', {
            'idea': idea,
            'questions': idea.generate_questions,
            'evidence_types': ['cloud', 'cloud-rain', 'cloud-sun'],
        })


def build(request):
    ideas = {
        'fact': request.POST['fact'],
        'definition': request.POST['definition'],
        'quality': request.POST['quality'],
        'counterpoint': request.POST['counterpoint'],
        'policy': request.POST['policy'],
    }
    thesis = Thesis(ideas)

    return JsonResponse(thesis.prepare())


def draft(request):
    elements = {
        'argument': request.POST['argument'],
        'claims': request.POST.getlist('claims[]'),
        'evidences': request.POST.getlist('evidences[]'),
        'entities': request.POST['entities'],
    }

    o = Draft(elements)
    return JsonResponse(o.generate())


def read(request):
    return render(request, 'essay/read.html')


def parse(request):
    article = Article(request.POST['content'])
    article.process()
    return render(request, 'essay/parse.html', {
        'parsed': article.parse(),
        'wc': article.words(),
        'keywords': article.keywords,
        'subjectivity': article.adjadv(),
    })

essay/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}&alpha;Write{% endblock title %}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/v4-shims.css">

    <style>
        body,html {
          font-size: 18px;
        }

    </style>
    {% block style %}
    {% endblock style %}
</head>

<body class="container-fluid bg-light">
    {% load static %}
    <div class="row h-75">
      <div class="col-sm-1">
          <div class="ml-4 mt-4"><a href="{% url 'essay:index' %}"><img class="img-fluid" src="{% static 'images/redwrite.png' %}" alt="alpha write" width="90%"></a></div>
      </div>
      <div class="col-sm-10">{% block content %}{% endblock content %}</div>
    </div>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-firestore.js"></script>

    <!-- TODO: Add SDKs for Firebase products that you want to use
         https://firebase.google.com/docs/web/setup#available-libraries -->
    <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-analytics.js"></script>

    <script>
      // Your web app's Firebase configuration
      var firebaseConfig = {
        apiKey: "AIzaSyAqs73R1cXNxJtgt9aGPgohSbjh37AompQ",
        authDomain: "alphawrite-b0822.firebaseapp.com",
        databaseURL: "https://alphawrite-b0822.firebaseio.com",
        projectId: "alphawrite-b0822",
        storageBucket: "alphawrite-b0822.appspot.com",
        messagingSenderId: "187084845321",
        appId: "1:187084845321:web:813a8e647b2130344163d8",
        measurementId: "G-3HZSVQK6BY"
      };
      // Initialize Firebase
      firebase.initializeApp(firebaseConfig);
      firebase.analytics();
    </script>
    <!--
    <script>
    const oneDay = 24 * 60 * 60 * 1000; // hours*minutes*seconds*milliseconds
    const firstDate = new Date(2020, 5, 7);
    const secondDate = new Date();

    const diffDays = Math.round(Math.abs((firstDate - secondDate) / oneDay));
    var n = document.getElementById("n");
    n.innerHTML = diffDays * 11 + Math.floor(Math.random() * 5);
    </script> -->
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>