alphawrite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('essay.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

essay/urls.py
from django.urls import path
from . import views

app_name = 'essay'
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('build', views.build, name='build'),
    path('questions', views.questions, name='questions'),
    path('draft', views.draft, name='draft'),
    path('read', views.read, name='read'),
    path('parse', views.parse, name='parse'),
    path('ideas', views.ideas, name='ideas'),
]

essay/models.py
import datetime
from collections import Counter

from django.db import models
from django.utils import timezone
import random
from .dictionary import Question
import spacy


class Thesis:
    def __init__(self, ideas):
        self.ideas = ideas

    def __str__(self):
        return self.build()

    def prepare(self):

        # build evidences

        fact = self.ideas.get("fact", "")

        definition = self.ideas.get("definition", "")

        quality = self.ideas.get("quality", "")

        counterpoint = self.ideas.get("counterpoint", "")

        evidences = [fact, definition, counterpoint]

        policy = self.ideas.get("policy", "")

        if quality and policy:
            argument = policy + " " + quality
        else:
            argument = policy + quality

        return {'argument': argument, 'evidences': evidences}


class Draft:
    def __init__(self, elements):
        self.type = ""
        self.structure = ""
        self.elements = elements
        self.argument = elements['argument']
        self.entities = elements['entities']
        self.claims = elements['claims']
        self.evidences = elements['evidences']

    def introduction(self):
        pass

    def generate(self):
        introduction = self.argument
        for c in self.claims:
            introduction += " " + c

        paragraphs = []

        paragraph_what = self.claims[0] + " " + self.evidences[0]
        paragraphs.append(paragraph_what)

        paragraph_nature = self.claims[1] + " " + self.evidences[1]
        paragraphs.append(paragraph_nature)

        if randrange(10) > 5:
            prefix_e = "One might object here that"
            prefix_c = "Nevertheless,"
        else:
            prefix_e = "On the one hand, I agree with some proponents that"
            prefix_c = "But on the other hand, I still insist that"
        counter_evidence = self.pack(prefix_e, self.evidences[2])
        counter_claim = self.pack(prefix_c, self.claims[2])

        paragraph_counter = counter_evidence + " " + counter_claim
        paragraphs.append(paragraph_counter)

        conclusion = introduction
        return {'introduction': introduction, 'paragraphs': paragraphs, 'conclusion': conclusion}

    def pack(self, prefix, sentence):
        packed = sentence
        first_word = packed.split(' ', 1)[0]
        if first_word not in self.entities:
            packed = packed[0].lower() + packed[1:]
        return prefix + " " + packed


# model for transition
class Transition:
    def __init__(self, category):
        self.category = category  # e.g., contrast

    def get_category(self):
        return self.category

    def get_phrases(self):
        """
        :param category: string
        :return (list): list of words in the given category
        """
        phrases = []

        cause_effect = ["Consequently", "Therefore", "Accordingly", "As a result",
                        "Hence", "Thus", "For this reason", "Due"]
        sequence = ["Furthermore", "In addition", "Moreover", "Finally",
                    "Again", "Until then", "In light of", "Again"]
        compare_contrast = ["similarly", "Likewise", "In the same fashion", "In the same way",
                            "In like manner", "Correspondingly", "Equally important", "Conversely", "In contrast",
                            "however", "On the contrary", "yet", "whereas"]
        example = ["For instance", "For example", "In fact", "Indeed", "of course",
                   "Equally important", "Specifically", "In other words"]
        purpose = ["Ultimately", "Evidently", "Without doubt", "Invariably", "To this end"]
        multiple = ["Couples with", "Together with", "vast array", "tapestry", "plethora"]

        if self.category == "cause_effect":
            phrases = cause_effect

        if self.category == "sequence":
            phrases = sequence

        return phrases

    def get_phrase(self):
        phrases = self.get_phrases()
        i = randrange(len(phrases))
        return phrases[i]


# model for active verbs
class Verb:
    def __init__(self, category):
        self.category = category

    def get_category(self):
        return self.category

    def get_verbs(self):
        """
        :param category: string
        :return (list): list of words in the given category
        """
        verbs = []

        literary = ["Consequently", "Therefore", "Accordingly", "As a result",
                    "Hence", "Thus", "For this reason", "Due"]
        research = ["Furthermore", "In addition", "Moreover", "Finally",
                    "Again", "Until then", "In light of", "Again"]
        beginnings = ["similarly", "Likewise", "In the same fashion", "In the same way",
                      "In like manner", "Correspondingly", "Equally important", "Conversely", "In contrast",
                      "however", "On the contrary", "yet", "whereas"]
        ideas = ["For instance", "For example", "In fact", "Indeed", "of course",
                 "Equally important", "Specifically", "In other words"]
        legal = ["Ultimately", "Evidently", "Without doubt", "Invariably", "To this end"]

        if self.category == "literary":
            verbs = literary

        if self.category == "beginnings":
            verbs = beginnings

        return verbs

    def get_verb(self):
        verbs = self.get_verbs()
        i = randrange(len(verbs))
        return verbs[i]


class Assignment:
    informative = ['inform', 'describe', 'define', 'review', 'notify', 'instruct', 'advise', 'announce', 'explain',
                   'demonstrate', 'illustrate', 'discuss', 'analyse', 'analyze']
    persuasive = ['persuade', 'convince', 'influence', 'argue', 'recommend', 'change', 'advocate', 'urge', 'defend',
                  'justify', 'support', 'to what extent', 'assess', 'evaluate', 'affect']

    subjects = ['Hitler', 'Mao', 'economic', 'finance']

    def __init__(self, assignment):
        self.purpose = "persuasive"
        self.topic = ""
        self.assignment = assignment

    def process(self):
        info = 0
        pers = 0
        for word in self.assignment.split():
            if word in self.informative:
                info += 1
            if word in self.persuasive:
                pers += 1
            if word in self.subjects:
                self.topic += word + " "
        if info > pers:
            self.purpose = "informative"

        return self

    def get_purpose(self):
        return self.purpose

    def get_topic(self):
        return self.topic


class Idea:
    def __init__(self, topic):
        self.topic = topic
        self.subject = ""
        self.verb = ""
        self.object = ""
        self.entities = ""
        self.processed = False
        self.questions = Question.dict

    def blocked(self):
        if '</script>' in self.topic:
            return True

        blacklist = [
            "test",
            "thisisatest",
            "whatsup",
        ]
        topic = ''.join(e for e in self.topic if e.isalnum()).lower()
        if topic.isdigit() or topic in blacklist or len(topic) < 2:
            return True

        if not self.processed:
            self.process()
        if not self.subject and not self.object and not len(self.entities):
            return True
        return False

    def process(self):
        if self.processed:
            return self

        nlp = spacy.load('en_core_web_sm')
        doc = nlp(self.topic)
        sentence = next(doc.sents)  # last sentence in prompt

        for word in sentence:
            if word.dep_ == 'nsubj':
                self.subject = word.text
            if word.dep_ in ['dobj', 'obj']:
                self.object = word.text
            if word.dep_ == 'ROOT':
                if word.pos_ == 'VERB':
                    self.verb = word.text.lower()
                if word.pos_ == 'NOUN' and not self.subject:
                    self.subject = word.text.lower()

        if self.subject:
            for chunk in doc.noun_chunks:
                if self.subject in chunk.text:
                    self.subject = chunk.text
                    break

        if self.object:
            for chunk in doc.noun_chunks:
                if self.object in chunk.text:
                    if 'What' not in chunk.text and 'Which' not in chunk.text:
                        self.object = chunk.text
                    break

        entities = []
        for ent in doc.ents:
            if ent.label_ in ['PERSON', 'ORG', 'EVENT', 'GPE', 'NORP']:
                entities.append(ent.text)

        ents = ""
        num_ents = len(entities)
        if num_ents:
            ents = entities[0]
            if num_ents == 2:
                ents += " and " + entities[1]
            elif num_ents > 2:  # 3 and more
                for i in range(1, num_ents - 1):
                    ents += ", " + entities[i]
                ents += ", and " + entities[num_ents - 1]

        self.entities = ents

        self.processed = True
        return self

    def generate_questions(self):
        q_fact = ['']
        q_definition = ['']
        q_quality = [''] * 2
        q_policy = ['']
        for badge, qs in self.questions.items():
            # replaced with subj, obj, and entities
            random.shuffle(qs)
            for question in qs:
                q = question.replace('{SUBJ}', '--' + self.subject + '--').replace('{OBJ}',
                                                                                   '--' + self.object + '--').replace(
                    '{ENTS}', '--' + self.entities + '--')
                if '----' not in q:
                    if '{F}' in q and not q_fact[0]:
                        q_fact[0] = q.replace('{F}', '').replace('--', '')
                    if '{D}' in q and not q_definition[0]:
                        q_definition[0] = q.replace('{D}', '').replace('--', '')

essay/views.py
from django.http import HttpResponseRedirect
from django.http import HttpResponse, JsonResponse

from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Transition, Verb, Thesis, Assignment, Idea, Draft
from .article import Article


def index(request):
    return render(request, 'essay/topic.html')


def dashboard(request):
    topic = request.POST['topic']
    idea = Idea(topic)

    if idea.blocked():
        return render(request, 'essay/index.html', {'idea': idea})
    else:
        return render(request, 'essay/dashboard.html', {
            'idea': idea,
            'evidence_types': ['cloud', 'cloud-rain', 'cloud-sun'],
        })


def questions(request):
    topic = request.POST['topic']
    stasis = request.POST['stasis']
    idea = Idea(topic)

    if idea.blocked():
        return
    else:
        return JsonResponse(idea.generate_question(stasis))


def ideas(request):
    topic = request.POST['topic']
    idea = Idea(topic)

    if idea.blocked():
        return render(request, 'essay/topic.html', {'idea': idea})
    else:
        return render(request, 'essay/ideas.html', {
            'idea': idea,
            'questions': idea.generate_questions,
            'evidence_types': ['cloud', 'cloud-rain', 'cloud-sun'],
        })


def build(request):
    ideas = {
        'fact': request.POST['fact'],
        'definition': request.POST['definition'],
        'quality': request.POST['quality'],
        'counterpoint': request.POST['counterpoint'],
        'policy': request.POST['policy'],
    }
    thesis = Thesis(ideas)

    return JsonResponse(thesis.prepare())


def draft(request):
    elements = {
        'argument': request.POST['argument'],
        'claims': request.POST.getlist('claims[]'),
        'evidences': request.POST.getlist('evidences[]'),
        'entities': request.POST['entities'],
    }

    o = Draft(elements)
    return JsonResponse(o.generate())


def read(request):
    return render(request, 'essay/read.html')


def parse(request):
    article = Article(request.POST['content'])
    article.process()
    return render(request, 'essay/parse.html', {
        'parsed': article.parse(),
        'wc': article.words(),
        'keywords': article.keywords,
        'subjectivity': article.adjadv(),
    })

essay/templates/essay/dashboard.html
{% extends "base.html" %}
{% block style %}
<style>
html,body{
   height:100%;
   width:100%;
}

textarea {
  width: 100%;
  outline: none;
  resize: none;
  overflow: hidden;
  border-width: 0 0 1px;
  border-color: #007bff;
}

textarea:focus {
  border-color: #d9534f;
}

.form-group {
  width: 90%;
  margin-bottom: 50px;
  position:relative;
  & + .form-group {
    margin-top: 10px;
  }
}

.form-label {
  position: absolute;
  left: 0;
  top: 5px;
  color: #007bff;
  background-color: #fff;
  z-index: 10;
  transition: transform 150ms ease-out, font-size 150ms ease-out;
}

.focused .form-label {
  transform: translateY(-125%);
  font-size: .75em;
  color: #d9534f;
}

.form-input {
  padding: 0;
}

.form-label.filled {
  color: #28a745;
}

.form-input.filled {
  border-color: #28a745;
}

.editable {
     display: inline-block;
     word-wrap: break-word;
     padding: 30px;
     background-color: #f3f3f3;
     border-radius: 3px;
     outline: 0;
}

.introduction-block {
  background-color: #f3c3c3;
}

.significance-block {
  background-color: #90f390;
}

[data-placeholder]:empty:before{
  content: attr(data-placeholder);
  pointer-events: none;
  display: block; /* For Firefox */
  font-style: italic;
}

</style>
{% endblock style%}
{% block content %}
<div class="container">
  <div class="mt-5 mb-4"><h4 class="debug">{{ idea.topic }}</h4></div>
  <ul class="nav nav-tabs nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#ideas" role="tab" aria-selected="true"><i class="fas fa-seedling"></i> Ideas</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" id="thesis-tab" data-toggle="tab" href="#thesis" role="tab" aria-controls="thesis" aria-selected="false"><i class="fas fa-apple-alt"></i> Thesis</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" id="draft-tab" data-toggle="tab" href="#draft" role="tab" aria-controls="draft" aria-selected="false"><i class="fas fa-layer-group"></i> Draft</a>
    </li>
    <li class="nav-item">
      <a class="nav-link disabled" data-toggle="tab" href="#proofreading" role="tab" aria-controls="proofreading" aria-selected="false"><i class="fas fa-eye"></i> Proofreading</a>
    </li>
  </ul>
  <div class="tab-content mt-5">
    <!-- ideas -->
    <div class="tab-pane fade show active" id="ideas" role="tabpanel" aria-labelledby="ideas-tab">
      {% for question in idea.generate_questions %}
      <div class="row justify-content-md-center">
        <div class="form-group">
          <label class="form-label bg-light" for="question-{{ forloop.counter0 }}">{{question}}</label>
          <textarea id="question-{{ forloop.counter0 }}" class="ideas form-input mb-2 bg-light" rows="1"></textarea>
        </div>
      </div>
      {% endfor %}
    </div>
    <!-- end of ideas -->

    <!-- thesis -->
    <div class="tab-pane fade" id="thesis" role="tabpanel" aria-labelledby="thesis-tab">
      <div class="container">
        <div class="row justify-content-md-center mb-2">
          <div class="col">
            <div id="argument" class="editable thesis" contenteditable="true"></div>
          </div>
        </div>
        <div class="row mb-2">
          <div class="col">
            <div id="claim-0" class="editable thesis" contenteditable="true" data-placeholder="How does the fact below demonstrate the truth of the claim above?"></div>
          </div>
          <div class="col">
            <div id="claim-1" class="editable thesis" contenteditable="true" data-placeholder="How does the concept below link to the argument above?"></div>
          </div>
          <div class="col">
            <div id="claim-2" class="editable thesis" contenteditable="true" data-placeholder="How does the argument above stand up to the counterargument below?"></div>
          </div>
        </div>
        <div class="row mb-2">
          {% for type in evidence_types %}
          <div class="col">
            <div  id="evidence-{{ forloop.counter0 }}" class="editable thesis" contenteditable="true"></div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="container justify-content-md-center mb-5" id="tentative-thesis">
        <p class="lead">
          <span id="thesis-argument" class="text-danger"></span>
          <span id="thesis-claim-0" class="text-success"></span>
          <span id="thesis-claim-1" class="text-info"></span>
          <span id="thesis-claim-2" class="text-primary"></span>
        </p>
      </div>
    </div>
    <!-- end of thesis -->

    <!-- draft -->
    <div class="tab-pane fade " id="draft" role="tabpanel" aria-labelledby="draft-tab">
      <div class="container">
        <p><strong>{{ idea.topic }}</strong></p>
        <p><span id="draft-introduction" class="editable introduction-block" contenteditable="true"></span><span class="editable significance-block" contenteditable="true">test</span></p>
        <p><span id="draft-paragraph-0" class="editable" contenteditable="true"></span></p>
        <p><span id="draft-paragraph-1" class="editable" contenteditable="true"></span></p>
        <p><span id="draft-paragraph-2" class="editable" contenteditable="true"></span></p>
        <p><span id="draft-conclusion" class="editable" contenteditable="true"></span></p>
      </div>
    </div>
    <!-- end of draft -->

    <!-- proofreading -->
    <div class="tab-pane fade" id="proofreading" role="tabpanel" aria-labelledby="proofreading-tab">
      <h4 class="text-danger"><i class="fas fa-shipping-fast"></i> ...</h4>
    </div>
    <!-- end of proofreading -->
  </div>
</div>
<div id="entities" class="invisible">{{idea.entities}}</div>
{% endblock content %}

{% block javascript %}
<script>

function debounce(func, wait, immediate) {
    var timeout;
    return function() {
        var context = this, args = arguments;
        var later = function() {
            timeout = null;
            if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
    };
};

$(function() {

  $('textarea').focus(function(){
    $(this).parents('.form-group').addClass('focused');
    $(this).removeClass("filled");
    $(this).siblings('.form-label').removeClass('filled');
  });

  $('textarea').blur(function(){
    var inputValue = $(this).val();
    if ( inputValue == "" ) {
      $(this).removeClass("filled");
      $(this).siblings('.form-label').removeClass('filled');
      $(this).parents('.form-group').removeClass('focused');
    } else {
      $(this).addClass("filled");
      $(this).siblings('.form-label').addClass('filled');
    }
  })

  $('.ideas').on('keypress keyup change click drop keydown cut paste', function() {
    $(this).height('auto');
    $(this).height($(this).prop('scrollHeight'));
  });

  $('.ideas').on('keyup paste', debounce(function() {
    if ($.trim($(this).val()) != "") {
      $(this).addClass("filled");
      $(this).siblings('.form-label').addClass('filled');
    }

    if ($('.ideas.filled').length >= $('.ideas').length - 1) {
      if ($('#thesis-tab').hasClass('disabled')) {
        $('#thesis-tab').removeClass('disabled');
      }
    }
  }, 500));

  $('.thesis').on('keyup keypress paste', debounce(function() {
    var e0 = $.trim($('#evidence-0').text());
    if (e0 != "") $('#question-0').val(e0);
    var e1 = $.trim($('#evidence-1').text());
    if (e1 != "") $('#question-1').val(e1);
    var e2 = $.trim($('#evidence-2').text());
    if (e2 != "") $('#question-3').val(e2);
    var ar = $.trim($('#argument').text());
    if (ar != "") $('#question-2').val(ar);

    $('#thesis-argument').html(ar);
    var i;
    for (i = 0; i < 3; i++) {
      $('#thesis-claim-' + String(i)).html($.trim($('#claim-' + String(i)).text()));
    }
    if ($('#draft-tab').hasClass('disabled')) {
      $('#draft-tab').removeClass('disabled');
    }

  }, 100));

  $('.nav-tabs a').on('shown.bs.tab', function(e){
    if ($(e.target).attr('id') == 'thesis-tab') {

      var db = firebase.firestore();

      db.collection("topics").add({
          topic: "{{ idea.topic }}"
      })
      .then(function(docRef) {
          console.log("Document written with ID: ", docRef.id);
      })
      .catch(function(error) {
          console.error("Error adding document: ", error);
      });

      var url = "{% url 'essay:build' %}";
      $.ajax({
        headers: {'X-CSRFToken': '{{csrf_token}}'},
        method: "POST",
        url: url,
        data: {
          fact: $.trim($('#question-0').val()),
          definition: $.trim($('#question-1').val()),
          quality: $.trim($('#question-2').val()),
          counterpoint: $.trim($('#question-3').val()),
          policy: $.trim($('#question-4').val()),
        },
        success: function (data) {
          if (data['argument'].length > 0) {
            $('#argument').html(data['argument']);
          }
          for (i=0; i<data['evidences'].length; i++) {
            $('#evidence-' + String(i)).html(data['evidences'][i]);
          }
        }
      });
    }
    if ($(e.target).attr('id') == 'draft-tab') {
      var url = "{% url 'essay:draft' %}";
      $.ajax({
        headers: {'X-CSRFToken': '{{csrf_token}}'},
        method: "POST",
        url: url,
        data: {
          argument: $.trim($('#argument').text()),
          entities: $('#entities').text(),
          'claims[]': [$.trim($('#claim-0').text()), $.trim($('#claim-1').text()), $.trim($('#claim-2').text())],
          'evidences[]': [$.trim($('#evidence-0').text()), $.trim($('#evidence-1').text()), $.trim($('#evidence-2').text())],
        },
        success: function (data) {
          $('#draft-introduction').html(data['introduction']);
          for (i=0; i<data['paragraphs'].length; i++) {
            $('#draft-paragraph-' + String(i)).html(data['paragraphs'][i]);
          }
          $('#draft-conclusion').html(data['conclusion']);
        }
      });
    }
  });

  var editors = document.querySelectorAll('div[contenteditable]');
  for(var i = 0, l = editors.length; i < l; i++) {
     editors[i].addEventListener('paste', myCustomPasteFunction);
  }

  function myCustomPasteFunction(e) {
   e.preventDefault();
   var text = e.clipboardData.getData("text/plain");
   document.execCommand("insertHTML", false, text);
  }

});
</script>
{% endblock javascript %}

essay/templates/essay/ideas.html
{% extends "base.html" %}
{% block style %}
<style>
html,body{
    height:100%;
}
</style>
{% endblock style%}

{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/cube.css'%}" type="text/css">
<div id="impress" data-transition-duration="2000">

    <div class="step" data-x="0" data-y="0" data-z="350"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-4 step-3 step-2 step-5 overview">
        <p>{{ idea.topic }}</p>
    </div>

    <div class="step" data-x="350" data-y="0" data-z="0" data-rotate-y="90"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-4 step-3 step-6 step-1 overview">
        <p>{{ questions.0 }}</p>
    </div>

    <div class="step" data-x="0" data-y="350" data-z="0" data-rotate-x="-90" data-rotate-z="90"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-2 step-5 step-6 step-1 overview">
        <p>{{ questions.1 }}</p>
    </div>

    <div class="step" data-x="0" data-y="-350" data-z="0" data-rotate-x="90" data-rotate-z="-90"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-5 step-2 step-6 step-1 overview">
        <p>{{ questions.2 }}</p>
    </div>

    <div class="step" data-x="-350" data-y="0" data-z="0" data-rotate-y="-90" data-rotate-z="-180"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-3 step-4 step-6 step-1 overview">
        <p>{{ questions.3 }}</p>
    </div>

    <div class="step" data-x="0" data-y="0" data-z="-350" data-rotate-y="-180" data-rotate-z="-180"
         data-goto-key-list="ArrowUp ArrowDown ArrowRight ArrowLeft o" data-goto-next-list="step-3 step-4 step-2 step-5 overview">
        <p>Slide six</p>
    </div>

    <div id="overview" class="step" data-x="700" data-y="-100" data-z="1000" data-scale="1" style="pointer-events: none;">
    </div>
</div>

<script src="{% static 'js/impress.js' %}"></script>
<script>impress().init();</script>

{% endblock content %}

essay/templates/essay/index.html
{% extends "base.html" %}
{% block style %}
<style>
html,body{
    height:100%;
}
</style>
{% endblock style%}

{% block content %}
<body class="bg-light">
  <div class="container-fluid h-75">
    <div class="h-50"></div>
    <div class="row h-25 justify-content-center">
      <div class="form-group w-50">
        <form action="{% url 'essay:dashboard' %}" method="post" class="form-inline">
          {% csrf_token %}
        <input type="text" class="form-control col-sm-9" name="topic" id="topic">
        <div class="form-group col-sm-1">
          <button type="submit" class="btn btn-primary"><i class="fas fa-angle-right"></i></button>
        </div>
        </form>
        <small>Topic, title, keywords, prompt, or assignment</small>
      </div>
    </div>
    {% if idea %}
      <div class="row justify-content-center">You: {{idea.topic}}<span class="text-success"><i class="fas fa-smile-wink"></i></span></div>
      <div class="row justify-content-center">Me: seriously?<span class="text-danger"><i class="fas fa-meh-rolling-eyes"></i></span></div>
    {% endif %}

  </div>
</body>
{% endblock content %}

{% block javascript %}
<script>
$(function() {
  $('button').click(function (e) {
    e.preventDefault();
    if ($.trim($('#topic').val()).length > 0) $('form').submit();
  });
});
</script>
{% endblock javascript %}

essay/templates/essay/parse.html
{% extends "base.html" %}
{% block style %}
<style>
html,body{
    height:100%;
}
</style>
{% endblock style%}

{% block content %}
<body class="bg-light">
  <div class="container-fluid h-75">
    <div class="row">&nbsp;</div>
    <div class="row">
      <h3>We've simplified the text from {{ wc.0 }} words to {{ wc.1 }} words for you.</h3>
    </div>
    <div class="row">
      <h5 class="text-secondary">
        {% for kw in keywords %}
            {{ kw }}
        {% endfor %}
        </h5>
    </div>
    <br><br>
    <div class="row">
      {{ parsed | linebreaks }}
    </div>
    <div class="row">
      <h6 class="text-secondary">{{ subjectivity }}</h6>
    </div>
  </div>
</body>
{% endblock content %}

essay/templates/essay/read.html
{% extends "base.html" %}
{% block style %}
<style>
.editable {
    border: none;
    overflow: hidden;
    outline: none;

    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    background: transparent;

    resize: none; /*remove the resize handle on the bottom right*/
    display: inline-block;
    word-wrap: break-word;
    border-radius: 3px;
}

[data-placeholder]:empty:before{
  content: attr(data-placeholder);
  pointer-events: none;
  display: block; /* For Firefox */
  color: #a3a3a3;
  font-size: 1.2em;
}
</style>
{% endblock style%}

{% block content %}
<body class="bg-light">
    <div class="row">&nbsp;</div>
    <p class="cursor"><span id="article" class="editable" contenteditable="true" data-placeholder="Copy and paste your article here."></span></p>
    <p>
      <form action="{% url 'essay:parse' %}" method="post">
          {% csrf_token %}
        <textarea name="content" id="content" type="hidden"></textarea>
        <div class="form-group">
          <button id="continue" type="submit" class="btn btn-primary">Continue</button>
        </div>
      </form>
    </p>
</body>
{% endblock content %}

{% block javascript %}
<script>
$(function() {
  $('#content').hide();
  $('#continue').hide();
  $('#article').focus();
  $('#article').on('paste', function() {
    $this = $(this);
    setTimeout(function() {
        $this.html($this.html().replace(/\<\/p\>/g," [br]").replace(/\<br\>/g," [br]").replace(/\<\/div\>/g," [br]").replace(/(<\/h)([0-6])>/g, " [br]"));
        // remove all the tags, and then replace the tokens for their original values
        $this.html($this.text().replace(/\[p\]/g, "<br>").replace(/\[br\]/g,"<br>").replace(/\[div\]/g,"<br>").replace(/(\[h\])([0-6])/g, "<br>"));
        $('#article').html($this.html());
    }, 100);
  });

  $('#article').keyup(function(){
    var c = $.trim($('#article').html());
    if (c.length == 0) {
        $('#continue').hide(100);
    } else {
      $('#continue').show(100);
    }
  });

  $('button').click(function (e) {
    e.preventDefault();
    var c = $.trim($('#article').html());
    if (c.length > 0) {
      $('#content').val(c);
      $('button').attr("disabled", true);
      $('form').submit();
    }
  });
});
</script>
{% endblock javascript %}